const prefix = 'settings'

export const SEND_PROFILE_CHANGES = `${prefix}/SEND_PROFILE_CHANGES`
export const SEND_PROFILE_CHANGES_SUCCESS = `${prefix}/SEND_PROFILE_CHANGES_SUCCESS`
export const SEND_PROFILE_CHANGES_FAILED = `${prefix}/SEND_PROFILE_CHANGES_FAILED`
export const CLEARED_PROFILE_NOTIFICATIONS = `${prefix}/CLEARED_PROFILE_NOTIFICATIONS`
